### PR TITLE
Fixes for Haapajoki

### PR DESCRIPTION
**Pull request by kimmoli**

### CODE REVIEW

**Comment by taaem** [comment]
Do we now have to provide bluez and obexd configs ourself in sparse/?
Otherwise LGTM

**Comment by kimmoli** [comment]
I don't know. @sledges ?
My work was purely based on a hunch after reading changelogs https://together.jolla.com/question/150236/changelog-205haapajoki/#150236-sbj-configs

**Comment by kimmoli** [comment]
Needs squashing

**Comment by kimmoli** [comment]
Note: There is upstream WIP for bluez/obexd packages
https://github.com/mer-hybris/droid-hal-configs/pull/65

**Comment by taaem** [comment]
So obexd and bt packages are in upstream dcd we don't need to provide them here right?

**Comment by kimmoli** [comment]
yes, https://github.com/mer-hybris/droid-hal-configs/pull/65

**Comment by taaem** [comment]
I would say we can drop them from here right?

**Comment by kimmoli** [comment]
yes, this is still WIP - updating soon. Just waited for that to be merged upstream.

**Comment by kimmoli** [comment]
Rebased and cleaned. @mlehtima dare to look through?
All commit messages are not as informative as they could. bare with me.

**Pull request merged**
