### PR TITLE
[patterns] remove non-working usb-moded stuff

### PR DESCRIPTION
**Pull request by kimmoli**

### CODE REVIEW

**Comment by taaem** [comment]
You tested it?

**Comment by kimmoli** [comment]
I have uninstalled those pkgs ages ago

**Review by taaem — APPROVED** [review]

**Comment by taaem** [comment]
MTP should still work right?

**Comment by mlehtima** [comment]
MTP is in usb-moded-pc-suite-mode-android so these changes will not affect MTP.

**Comment by kimmoli** [comment]
fisu

**Pull request merged**
