### PR TITLE
Add Multisim

### PR DESCRIPTION
**Pull request by taaem**
https://github.com/kimmoli/sfos-onyx-issues/issues/10

### CODE REVIEW

**Review by kimmoli — APPROVED** [review]

**Review by kimmoli — COMMENTED** [review]
This file is already provided by ofono-configs-mer-1.17+git22-10.1.1.jolla.armv7hl
So does adding this here cause conflict?

**Comment by kimmoli** [comment]
/etc/ofono/ril_subscription.conf  is already provided by ofono-configs-mer-1.17+git22-10.1.1.jolla.armv7hl
So does adding this here cause conflict?

**Comment by taaem** [comment]
https://github.com/mlehtima/droid-config-fp2-sibon/blob/master/rpm/droid-config-fp2-sibon.spec#L15 Probably need to add this

**Comment by kimmoli** [comment]
Yes. ofono-configs-mer-\* provides just that file, /etc/ofono/ril_subscription.conf.

**Pull request merged**
